// Single source of truth for all subjects offered on the platform.
// `available` = questions exist and are live.
// `comingSoon` = planned but not yet launched.

export const ALL_SUBJECTS = [
  {
    id: 'chemistry_s1',
    name: 'Chemistry',
    stage: 'Stage 1',
    icon: '⚗️',
    color: '#f1be43',
    topics: ['Atomic Structure', 'Bonding', 'Quantities', 'Periodic Table', 'Solutions', 'Acid–Base', 'Redox'],
    questionCount: 50,
    available: true,
  },
  {
    id: 'chemistry_s2',
    name: 'Chemistry',
    stage: 'Stage 2',
    icon: '⚗️',
    color: '#f9d87a',
    topics: ['Monitoring the Environment', 'Chemical Processes', 'Organic Chemistry', 'Managing Resources'],
    questionCount: 15,
    available: true,
  },
  {
    id: 'biology_s1',
    name: 'Biology',
    stage: 'Stage 1',
    icon: '🧬',
    color: '#10b981',
    topics: ['Cells', 'Genetics', 'Evolution', 'Ecosystems'],
    questionCount: 0,
    available: false,
    comingSoon: true,
  },
  {
    id: 'biology_s2',
    name: 'Biology',
    stage: 'Stage 2',
    icon: '🧬',
    color: '#10b981',
    topics: ['DNA & Proteins', 'Cellular Processes', 'Evolution', 'Biodiversity'],
    questionCount: 0,
    available: false,
    comingSoon: true,
  },
  {
    id: 'physics_s1',
    name: 'Physics',
    stage: 'Stage 1',
    icon: '⚛️',
    color: '#f59e0b',
    topics: ['Motion', 'Forces', 'Energy', 'Waves'],
    questionCount: 0,
    available: false,
    comingSoon: true,
  },
  {
    id: 'physics_s2',
    name: 'Physics',
    stage: 'Stage 2',
    icon: '⚛️',
    color: '#f59e0b',
    topics: ['Motion', 'Electricity', 'Waves', 'Modern Physics'],
    questionCount: 0,
    available: false,
    comingSoon: true,
  },
  {
    id: 'maths_methods_s2',
    name: 'Mathematical Methods',
    stage: 'Stage 2',
    icon: '∫',
    color: '#6366f1',
    topics: ['Differentiation', 'Integration', 'Functions', 'Probability'],
    questionCount: 0,
    available: false,
    comingSoon: true,
  },
  {
    id: 'english_s2',
    name: 'English Literary Studies',
    stage: 'Stage 2',
    icon: '📖',
    color: '#ec4899',
    topics: ['Close Analysis', 'Essay Writing', 'Comparative Study'],
    questionCount: 0,
    available: false,
    comingSoon: true,
  },
]
