// Periodic table dataset for the in-quiz reference tool.
// Each element: { n, sym, name, mass, group, period, cat, x, y }
//   x / y are 1-indexed CSS grid coordinates (18 columns).
//   f-block (lanthanides/actinides) live on rows 9 and 10 with a one-row gap.
//   `mass` is the standard atomic weight (rounded); synthetic elements use the
//   most-stable isotope mass in [brackets] form as a number.

export const CATEGORIES = {
  'alkali-metal':        { label: 'Alkali metal',          color: '#f87171' },
  'alkaline-earth':      { label: 'Alkaline earth metal',  color: '#fb923c' },
  'transition-metal':    { label: 'Transition metal',      color: '#fbbf24' },
  'post-transition':     { label: 'Post-transition metal', color: '#a3e635' },
  'metalloid':           { label: 'Metalloid',             color: '#34d399' },
  'reactive-nonmetal':   { label: 'Reactive nonmetal',     color: '#22d3ee' },
  'noble-gas':           { label: 'Noble gas',             color: '#818cf8' },
  'lanthanide':          { label: 'Lanthanide',            color: '#e879f9' },
  'actinide':            { label: 'Actinide',              color: '#f472b6' },
  'unknown':             { label: 'Unknown properties',    color: '#94a3b8' },
}

// prettier-ignore
export const ELEMENTS = [
  { n: 1,  sym: 'H',  name: 'Hydrogen',     mass: 1.008,   group: 1,  period: 1, cat: 'reactive-nonmetal', x: 1,  y: 1 },
  { n: 2,  sym: 'He', name: 'Helium',       mass: 4.003,   group: 18, period: 1, cat: 'noble-gas',         x: 18, y: 1 },
  { n: 3,  sym: 'Li', name: 'Lithium',      mass: 6.941,   group: 1,  period: 2, cat: 'alkali-metal',      x: 1,  y: 2 },
  { n: 4,  sym: 'Be', name: 'Beryllium',    mass: 9.012,   group: 2,  period: 2, cat: 'alkaline-earth',    x: 2,  y: 2 },
  { n: 5,  sym: 'B',  name: 'Boron',        mass: 10.811,  group: 13, period: 2, cat: 'metalloid',         x: 13, y: 2 },
  { n: 6,  sym: 'C',  name: 'Carbon',       mass: 12.011,  group: 14, period: 2, cat: 'reactive-nonmetal', x: 14, y: 2 },
  { n: 7,  sym: 'N',  name: 'Nitrogen',     mass: 14.007,  group: 15, period: 2, cat: 'reactive-nonmetal', x: 15, y: 2 },
  { n: 8,  sym: 'O',  name: 'Oxygen',       mass: 15.999,  group: 16, period: 2, cat: 'reactive-nonmetal', x: 16, y: 2 },
  { n: 9,  sym: 'F',  name: 'Fluorine',     mass: 18.998,  group: 17, period: 2, cat: 'reactive-nonmetal', x: 17, y: 2 },
  { n: 10, sym: 'Ne', name: 'Neon',         mass: 20.180,  group: 18, period: 2, cat: 'noble-gas',         x: 18, y: 2 },
  { n: 11, sym: 'Na', name: 'Sodium',       mass: 22.990,  group: 1,  period: 3, cat: 'alkali-metal',      x: 1,  y: 3 },
  { n: 12, sym: 'Mg', name: 'Magnesium',    mass: 24.305,  group: 2,  period: 3, cat: 'alkaline-earth',    x: 2,  y: 3 },
  { n: 13, sym: 'Al', name: 'Aluminium',    mass: 26.982,  group: 13, period: 3, cat: 'post-transition',   x: 13, y: 3 },
  { n: 14, sym: 'Si', name: 'Silicon',      mass: 28.086,  group: 14, period: 3, cat: 'metalloid',         x: 14, y: 3 },
  { n: 15, sym: 'P',  name: 'Phosphorus',   mass: 30.974,  group: 15, period: 3, cat: 'reactive-nonmetal', x: 15, y: 3 },
  { n: 16, sym: 'S',  name: 'Sulfur',       mass: 32.066,  group: 16, period: 3, cat: 'reactive-nonmetal', x: 16, y: 3 },
  { n: 17, sym: 'Cl', name: 'Chlorine',     mass: 35.453,  group: 17, period: 3, cat: 'reactive-nonmetal', x: 17, y: 3 },
  { n: 18, sym: 'Ar', name: 'Argon',        mass: 39.948,  group: 18, period: 3, cat: 'noble-gas',         x: 18, y: 3 },
  { n: 19, sym: 'K',  name: 'Potassium',    mass: 39.098,  group: 1,  period: 4, cat: 'alkali-metal',      x: 1,  y: 4 },
  { n: 20, sym: 'Ca', name: 'Calcium',      mass: 40.078,  group: 2,  period: 4, cat: 'alkaline-earth',    x: 2,  y: 4 },
  { n: 21, sym: 'Sc', name: 'Scandium',     mass: 44.956,  group: 3,  period: 4, cat: 'transition-metal',  x: 3,  y: 4 },
  { n: 22, sym: 'Ti', name: 'Titanium',     mass: 47.867,  group: 4,  period: 4, cat: 'transition-metal',  x: 4,  y: 4 },
  { n: 23, sym: 'V',  name: 'Vanadium',     mass: 50.942,  group: 5,  period: 4, cat: 'transition-metal',  x: 5,  y: 4 },
  { n: 24, sym: 'Cr', name: 'Chromium',     mass: 51.996,  group: 6,  period: 4, cat: 'transition-metal',  x: 6,  y: 4 },
  { n: 25, sym: 'Mn', name: 'Manganese',    mass: 54.938,  group: 7,  period: 4, cat: 'transition-metal',  x: 7,  y: 4 },
  { n: 26, sym: 'Fe', name: 'Iron',         mass: 55.845,  group: 8,  period: 4, cat: 'transition-metal',  x: 8,  y: 4 },
  { n: 27, sym: 'Co', name: 'Cobalt',       mass: 58.933,  group: 9,  period: 4, cat: 'transition-metal',  x: 9,  y: 4 },
  { n: 28, sym: 'Ni', name: 'Nickel',       mass: 58.693,  group: 10, period: 4, cat: 'transition-metal',  x: 10, y: 4 },
  { n: 29, sym: 'Cu', name: 'Copper',       mass: 63.546,  group: 11, period: 4, cat: 'transition-metal',  x: 11, y: 4 },
  { n: 30, sym: 'Zn', name: 'Zinc',         mass: 65.38,   group: 12, period: 4, cat: 'transition-metal',  x: 12, y: 4 },
  { n: 31, sym: 'Ga', name: 'Gallium',      mass: 69.723,  group: 13, period: 4, cat: 'post-transition',   x: 13, y: 4 },
  { n: 32, sym: 'Ge', name: 'Germanium',    mass: 72.631,  group: 14, period: 4, cat: 'metalloid',         x: 14, y: 4 },
  { n: 33, sym: 'As', name: 'Arsenic',      mass: 74.922,  group: 15, period: 4, cat: 'metalloid',         x: 15, y: 4 },
  { n: 34, sym: 'Se', name: 'Selenium',     mass: 78.971,  group: 16, period: 4, cat: 'reactive-nonmetal', x: 16, y: 4 },
  { n: 35, sym: 'Br', name: 'Bromine',      mass: 79.904,  group: 17, period: 4, cat: 'reactive-nonmetal', x: 17, y: 4 },
  { n: 36, sym: 'Kr', name: 'Krypton',      mass: 83.798,  group: 18, period: 4, cat: 'noble-gas',         x: 18, y: 4 },
  { n: 37, sym: 'Rb', name: 'Rubidium',     mass: 85.468,  group: 1,  period: 5, cat: 'alkali-metal',      x: 1,  y: 5 },
  { n: 38, sym: 'Sr', name: 'Strontium',    mass: 87.62,   group: 2,  period: 5, cat: 'alkaline-earth',    x: 2,  y: 5 },
  { n: 39, sym: 'Y',  name: 'Yttrium',      mass: 88.906,  group: 3,  period: 5, cat: 'transition-metal',  x: 3,  y: 5 },
  { n: 40, sym: 'Zr', name: 'Zirconium',    mass: 91.224,  group: 4,  period: 5, cat: 'transition-metal',  x: 4,  y: 5 },
  { n: 41, sym: 'Nb', name: 'Niobium',      mass: 92.906,  group: 5,  period: 5, cat: 'transition-metal',  x: 5,  y: 5 },
  { n: 42, sym: 'Mo', name: 'Molybdenum',   mass: 95.95,   group: 6,  period: 5, cat: 'transition-metal',  x: 6,  y: 5 },
  { n: 43, sym: 'Tc', name: 'Technetium',   mass: 98,      group: 7,  period: 5, cat: 'transition-metal',  x: 7,  y: 5 },
  { n: 44, sym: 'Ru', name: 'Ruthenium',    mass: 101.07,  group: 8,  period: 5, cat: 'transition-metal',  x: 8,  y: 5 },
  { n: 45, sym: 'Rh', name: 'Rhodium',      mass: 102.906, group: 9,  period: 5, cat: 'transition-metal',  x: 9,  y: 5 },
  { n: 46, sym: 'Pd', name: 'Palladium',    mass: 106.42,  group: 10, period: 5, cat: 'transition-metal',  x: 10, y: 5 },
  { n: 47, sym: 'Ag', name: 'Silver',       mass: 107.868, group: 11, period: 5, cat: 'transition-metal',  x: 11, y: 5 },
  { n: 48, sym: 'Cd', name: 'Cadmium',      mass: 112.414, group: 12, period: 5, cat: 'transition-metal',  x: 12, y: 5 },
  { n: 49, sym: 'In', name: 'Indium',       mass: 114.818, group: 13, period: 5, cat: 'post-transition',   x: 13, y: 5 },
  { n: 50, sym: 'Sn', name: 'Tin',          mass: 118.711, group: 14, period: 5, cat: 'post-transition',   x: 14, y: 5 },
  { n: 51, sym: 'Sb', name: 'Antimony',     mass: 121.760, group: 15, period: 5, cat: 'metalloid',         x: 15, y: 5 },
  { n: 52, sym: 'Te', name: 'Tellurium',    mass: 127.6,   group: 16, period: 5, cat: 'metalloid',         x: 16, y: 5 },
  { n: 53, sym: 'I',  name: 'Iodine',       mass: 126.904, group: 17, period: 5, cat: 'reactive-nonmetal', x: 17, y: 5 },
  { n: 54, sym: 'Xe', name: 'Xenon',        mass: 131.293, group: 18, period: 5, cat: 'noble-gas',         x: 18, y: 5 },
  { n: 55, sym: 'Cs', name: 'Caesium',      mass: 132.905, group: 1,  period: 6, cat: 'alkali-metal',      x: 1,  y: 6 },
  { n: 56, sym: 'Ba', name: 'Barium',       mass: 137.328, group: 2,  period: 6, cat: 'alkaline-earth',    x: 2,  y: 6 },
  { n: 57, sym: 'La', name: 'Lanthanum',    mass: 138.905, group: 3,  period: 6, cat: 'lanthanide',        x: 3,  y: 9 },
  { n: 58, sym: 'Ce', name: 'Cerium',       mass: 140.116, group: 3,  period: 6, cat: 'lanthanide',        x: 4,  y: 9 },
  { n: 59, sym: 'Pr', name: 'Praseodymium', mass: 140.908, group: 3,  period: 6, cat: 'lanthanide',        x: 5,  y: 9 },
  { n: 60, sym: 'Nd', name: 'Neodymium',    mass: 144.243, group: 3,  period: 6, cat: 'lanthanide',        x: 6,  y: 9 },
  { n: 61, sym: 'Pm', name: 'Promethium',   mass: 145,     group: 3,  period: 6, cat: 'lanthanide',        x: 7,  y: 9 },
  { n: 62, sym: 'Sm', name: 'Samarium',     mass: 150.36,  group: 3,  period: 6, cat: 'lanthanide',        x: 8,  y: 9 },
  { n: 63, sym: 'Eu', name: 'Europium',     mass: 151.964, group: 3,  period: 6, cat: 'lanthanide',        x: 9,  y: 9 },
  { n: 64, sym: 'Gd', name: 'Gadolinium',   mass: 157.25,  group: 3,  period: 6, cat: 'lanthanide',        x: 10, y: 9 },
  { n: 65, sym: 'Tb', name: 'Terbium',      mass: 158.925, group: 3,  period: 6, cat: 'lanthanide',        x: 11, y: 9 },
  { n: 66, sym: 'Dy', name: 'Dysprosium',   mass: 162.500, group: 3,  period: 6, cat: 'lanthanide',        x: 12, y: 9 },
  { n: 67, sym: 'Ho', name: 'Holmium',      mass: 164.930, group: 3,  period: 6, cat: 'lanthanide',        x: 13, y: 9 },
  { n: 68, sym: 'Er', name: 'Erbium',       mass: 167.259, group: 3,  period: 6, cat: 'lanthanide',        x: 14, y: 9 },
  { n: 69, sym: 'Tm', name: 'Thulium',      mass: 168.934, group: 3,  period: 6, cat: 'lanthanide',        x: 15, y: 9 },
  { n: 70, sym: 'Yb', name: 'Ytterbium',    mass: 173.055, group: 3,  period: 6, cat: 'lanthanide',        x: 16, y: 9 },
  { n: 71, sym: 'Lu', name: 'Lutetium',     mass: 174.967, group: 3,  period: 6, cat: 'lanthanide',        x: 17, y: 9 },
  { n: 72, sym: 'Hf', name: 'Hafnium',      mass: 178.49,  group: 4,  period: 6, cat: 'transition-metal',  x: 4,  y: 6 },
  { n: 73, sym: 'Ta', name: 'Tantalum',     mass: 180.948, group: 5,  period: 6, cat: 'transition-metal',  x: 5,  y: 6 },
  { n: 74, sym: 'W',  name: 'Tungsten',     mass: 183.84,  group: 6,  period: 6, cat: 'transition-metal',  x: 6,  y: 6 },
  { n: 75, sym: 'Re', name: 'Rhenium',      mass: 186.207, group: 7,  period: 6, cat: 'transition-metal',  x: 7,  y: 6 },
  { n: 76, sym: 'Os', name: 'Osmium',       mass: 190.23,  group: 8,  period: 6, cat: 'transition-metal',  x: 8,  y: 6 },
  { n: 77, sym: 'Ir', name: 'Iridium',      mass: 192.217, group: 9,  period: 6, cat: 'transition-metal',  x: 9,  y: 6 },
  { n: 78, sym: 'Pt', name: 'Platinum',     mass: 195.085, group: 10, period: 6, cat: 'transition-metal',  x: 10, y: 6 },
  { n: 79, sym: 'Au', name: 'Gold',         mass: 196.967, group: 11, period: 6, cat: 'transition-metal',  x: 11, y: 6 },
  { n: 80, sym: 'Hg', name: 'Mercury',      mass: 200.592, group: 12, period: 6, cat: 'transition-metal',  x: 12, y: 6 },
  { n: 81, sym: 'Tl', name: 'Thallium',     mass: 204.383, group: 13, period: 6, cat: 'post-transition',   x: 13, y: 6 },
  { n: 82, sym: 'Pb', name: 'Lead',         mass: 207.2,   group: 14, period: 6, cat: 'post-transition',   x: 14, y: 6 },
  { n: 83, sym: 'Bi', name: 'Bismuth',      mass: 208.980, group: 15, period: 6, cat: 'post-transition',   x: 15, y: 6 },
  { n: 84, sym: 'Po', name: 'Polonium',     mass: 209,     group: 16, period: 6, cat: 'post-transition',   x: 16, y: 6 },
  { n: 85, sym: 'At', name: 'Astatine',     mass: 210,     group: 17, period: 6, cat: 'metalloid',         x: 17, y: 6 },
  { n: 86, sym: 'Rn', name: 'Radon',        mass: 222,     group: 18, period: 6, cat: 'noble-gas',         x: 18, y: 6 },
  { n: 87, sym: 'Fr', name: 'Francium',     mass: 223,     group: 1,  period: 7, cat: 'alkali-metal',      x: 1,  y: 7 },
  { n: 88, sym: 'Ra', name: 'Radium',       mass: 226,     group: 2,  period: 7, cat: 'alkaline-earth',    x: 2,  y: 7 },
  { n: 89, sym: 'Ac', name: 'Actinium',     mass: 227,     group: 3,  period: 7, cat: 'actinide',          x: 3,  y: 10 },
  { n: 90, sym: 'Th', name: 'Thorium',      mass: 232.038, group: 3,  period: 7, cat: 'actinide',          x: 4,  y: 10 },
  { n: 91, sym: 'Pa', name: 'Protactinium', mass: 231.036, group: 3,  period: 7, cat: 'actinide',          x: 5,  y: 10 },
  { n: 92, sym: 'U',  name: 'Uranium',      mass: 238.029, group: 3,  period: 7, cat: 'actinide',          x: 6,  y: 10 },
  { n: 93, sym: 'Np', name: 'Neptunium',    mass: 237,     group: 3,  period: 7, cat: 'actinide',          x: 7,  y: 10 },
  { n: 94, sym: 'Pu', name: 'Plutonium',    mass: 244,     group: 3,  period: 7, cat: 'actinide',          x: 8,  y: 10 },
  { n: 95, sym: 'Am', name: 'Americium',    mass: 243,     group: 3,  period: 7, cat: 'actinide',          x: 9,  y: 10 },
  { n: 96, sym: 'Cm', name: 'Curium',       mass: 247,     group: 3,  period: 7, cat: 'actinide',          x: 10, y: 10 },
  { n: 97, sym: 'Bk', name: 'Berkelium',    mass: 247,     group: 3,  period: 7, cat: 'actinide',          x: 11, y: 10 },
  { n: 98, sym: 'Cf', name: 'Californium',  mass: 251,     group: 3,  period: 7, cat: 'actinide',          x: 12, y: 10 },
  { n: 99, sym: 'Es', name: 'Einsteinium',  mass: 252,     group: 3,  period: 7, cat: 'actinide',          x: 13, y: 10 },
  { n: 100,sym: 'Fm', name: 'Fermium',      mass: 257,     group: 3,  period: 7, cat: 'actinide',          x: 14, y: 10 },
  { n: 101,sym: 'Md', name: 'Mendelevium',  mass: 258,     group: 3,  period: 7, cat: 'actinide',          x: 15, y: 10 },
  { n: 102,sym: 'No', name: 'Nobelium',     mass: 259,     group: 3,  period: 7, cat: 'actinide',          x: 16, y: 10 },
  { n: 103,sym: 'Lr', name: 'Lawrencium',   mass: 262,     group: 3,  period: 7, cat: 'actinide',          x: 17, y: 10 },
  { n: 104,sym: 'Rf', name: 'Rutherfordium',mass: 267,     group: 4,  period: 7, cat: 'transition-metal',  x: 4,  y: 7 },
  { n: 105,sym: 'Db', name: 'Dubnium',      mass: 268,     group: 5,  period: 7, cat: 'transition-metal',  x: 5,  y: 7 },
  { n: 106,sym: 'Sg', name: 'Seaborgium',   mass: 269,     group: 6,  period: 7, cat: 'transition-metal',  x: 6,  y: 7 },
  { n: 107,sym: 'Bh', name: 'Bohrium',      mass: 270,     group: 7,  period: 7, cat: 'transition-metal',  x: 7,  y: 7 },
  { n: 108,sym: 'Hs', name: 'Hassium',      mass: 269,     group: 8,  period: 7, cat: 'transition-metal',  x: 8,  y: 7 },
  { n: 109,sym: 'Mt', name: 'Meitnerium',   mass: 278,     group: 9,  period: 7, cat: 'unknown',           x: 9,  y: 7 },
  { n: 110,sym: 'Ds', name: 'Darmstadtium', mass: 281,     group: 10, period: 7, cat: 'unknown',           x: 10, y: 7 },
  { n: 111,sym: 'Rg', name: 'Roentgenium',  mass: 282,     group: 11, period: 7, cat: 'unknown',           x: 11, y: 7 },
  { n: 112,sym: 'Cn', name: 'Copernicium',  mass: 285,     group: 12, period: 7, cat: 'unknown',           x: 12, y: 7 },
  { n: 113,sym: 'Nh', name: 'Nihonium',     mass: 286,     group: 13, period: 7, cat: 'unknown',           x: 13, y: 7 },
  { n: 114,sym: 'Fl', name: 'Flerovium',    mass: 289,     group: 14, period: 7, cat: 'unknown',           x: 14, y: 7 },
  { n: 115,sym: 'Mc', name: 'Moscovium',    mass: 290,     group: 15, period: 7, cat: 'unknown',           x: 15, y: 7 },
  { n: 116,sym: 'Lv', name: 'Livermorium',  mass: 293,     group: 16, period: 7, cat: 'unknown',           x: 16, y: 7 },
  { n: 117,sym: 'Ts', name: 'Tennessine',   mass: 294,     group: 17, period: 7, cat: 'unknown',           x: 17, y: 7 },
  { n: 118,sym: 'Og', name: 'Oganesson',    mass: 294,     group: 18, period: 7, cat: 'noble-gas',         x: 18, y: 7 },
]
