kind = "mobile"
previewPath = "/mobile/"
title = "gradefarm. Mobile"
version = "1.0.0"
id = "artifacts/gradefarm-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/mobile/" ]
localPort = 22059

[services.development]
run = "pnpm --filter @workspace/gradefarm-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/gradefarm-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/gradefarm-mobile", "run", "serve" ]

[services.env]
PORT = "22059"
BASE_PATH = "/mobile/"
